include:
  # Automatically build Docker images
  - project: 'world/ci-templates'
    file: '/gitlab-ci/docker-v1.yml'
  # Use standard release to automatically trigger releases
  # See https://git.novadiscovery.net/world/ci-template/standard-release
  - project: 'world/ci-template/standard-release'
    ref: v2
    file: '/templates/.gitlab-ci-release.yml'

stages:
  - build
  - test
  - release

workflow:
  rules:
    # Prevent pipeline when a MR is created
    - if: $CI_MERGE_REQUEST_ID
      when: never
    # Else, run pipeline
    - when: always

variables:
  DOCKER_BUILDKIT: 1

# A simple test of Novops usage with files and variables
test-simple:
  stage: test
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  script:
  - apk add bash
  - tests/test.sh
  rules:
  - if: $CI_COMMIT_BRANCH != "master" && $CI_COMMIT_TAG == null

# Override stage (standard-release) by default
job:release:
  stage: release
  
