# The unique application name
name: example-app

# Set of existing environments
# Each environment defined files and variables to load
environments:

  # The dev environment
  dev:

    # Set of variables to load in environment
    variables:

      # Variable with plain value
      - name: MY_APP_HOST
        value: "localhost"
      
      # Variable loaded from a Bitwarden entry
      # Required Bitwarden CLI to be installed locally
      - name: AWS_SECRET_ACCESS_KEY
        value:
          bitwarden:
            # Name of the entry to load from
            # Required
            entry: "Novops test - login.password entry"

            # Name of the field in entry to load in entry's JSON
            # See format with bw get item "xxx"
            # For Login: use 'login.password'
            # For Secure Note: use 'notes'
            field: login.password

    # Set of files to load
    #
    # By default, files will be saved under /run/user/<uid>/novops/<project>/<environment>/<file>
    # i.e. /run/user/1000/novops/example-app/dev/dog
    # 
    # Variable specify an environment variable name which will be exported
    # pointing to file path
    # By default, will be generated with format NOVOPS_<APP>_<ENV>_FILE_<NAME>
    # such as NOVOPS_EXAMPLE_APP_DEV_FILE_DOG="/run/user/1000/novops/example-app/dev/dog"
    #
    files: 
      - name: dog
        content: "woof"

      - content: "meow"
        variable: CAT_LOCATION
        dest: /tmp/cat

      - content:
          bitwarden:
            entry: Novops test - notes entry
            field: notes

    aws:
      assume_role:
        role_arn: arn:aws:iam::419998656076:role/deployinfra_dev_deploy
        source_profile: nova-sandbox
          
# Default values
default:
  environment: dev
