[package]
name = "novops"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
enum_dispatch = "0.3.8"
clap = { version = "3.2.6", features = ["derive"] }
xdg = "^2.1"
text_io = "0.1.10"
log = "0.4"
log4rs = "1.1.1"