[package]
name = "novops"
version = "0.1.9"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
enum_dispatch = "0.3.8"
clap = { version = "3.2.6", features = ["derive"] }
xdg = "^2.1"
text_io = "0.1.10"
log = "0.4"
log4rs = "1.1.1"
users = "0.11"
aws-sdk-sts = "0.14.0"
aws-sdk-iam = "0.14.0"
aws-config = "0.14.0"
tokio = { version = "1", features = ["full"] }
convert_case = "0.5.0"
async-trait = "0.1.56"
anyhow = { version = "1.0", features = ["backtrace"] }
rand = "0.5"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]