[target.aarch64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update && apt-get install --assume-yes libssl-dev:arm64"
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture amd64",
    "apt-get update && apt-get install --assume-yes libssl-dev:amd64"
]


[target.x86_64-apple-darwin]
image = "x86_64-apple-darwin-cross:local"

[target.aarch64-apple-darwin]
image = "aarch64-apple-darwin-cross:local"