[book]
authors = ["Pierre Beucher"]
language = "en"
multilingual = false
src = "src"
title = "novops documentation"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/PierreBeucher/novops"
edit-url-template = "https://github.com/PierreBeucher/novops/edit/main/docs/{path}"

# [output.linkcheck]