[book]
authors = ["Pierre Beucher"]
language = "en"
multilingual = false
src = "src"
title = "novops documentation"

[output.html]
git-repository-url = "https://github.com/novadiscovery/novops"
edit-url-template = "https://github.com/novadiscovery/novops/edit/main/docs/{path}"
