name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: "type=local,dest=novops-build"

      - uses: montudor/action-zip@v1
        with:
          args: zip -j novops-${{ runner.arch }}-${{ runner.os }}.zip novops-build/novops

      - run: sha256sum novops-${{ runner.arch }}-${{ runner.os }}.zip > novops-${{ runner.arch }}-${{ runner.os }}.zip.sha256sum

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            novops-${{ runner.arch }}-${{ runner.os }}.zip
            novops-${{ runner.arch }}-${{ runner.os }}.zip.sha256sum
          body: See [CHANGELOG](https://github.com/novadiscovery/novops/blob/main/CHANGELOG.md)