name: Publish release artifacts

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pull-requests: write

jobs:
  build_publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: "type=local,dest=novops-build"

      - name: Zip artifact
        uses: montudor/action-zip@v1
        with:
          args: zip -j novops-${{ runner.arch }}-${{ runner.os }}.zip novops-build/novops
       
      - name: Artifact checksum
        run: sha256sum novops-${{ runner.arch }}-${{ runner.os }}.zip > novops-${{ runner.arch }}-${{ runner.os }}.zip.sha256sum

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release upload $GITHUB_REF_NAME
          novops-$RUNNER_ARCH-$RUNNER_OS.zip 
          novops-$RUNNER_ARCH-$RUNNER_OS.zip.sha256sum